### ISSUE TITLE
Quicklook to show what is on clipboard before send it to gist

### ISSUE THREAD

**Issue by unnamedd** [Bunn/macGist#4]
We need to have some confirmation before sending the content from clipboard to gist, to avoid send undesirable content.

Reference:
https://developer.apple.com/documentation/quicklook/qlpreviewcontroller

**Comment by Bunn** [comment]
@unnamedd yep, this is something that I was thinking about as well. I'm just not sure how to display it without disrupting the UI too much.

**Comment by unnamedd** [comment]
@bunn take a look to reference in the description. I guess it will help us.

**Comment by Bunn** [comment]
@unnamedd I'm not talking about how to do it technically, I'm just not sure yet on how to display the content before sending it to gist without disrupting the UX too much.
Like, where it should be displayed? When? Will it add more clicks to the user? This type of thing, not sure of how to do it yet.

Since you can delete anonymous (if you open on the same machine/ip) and authenticated content on Gist, I don't think this is a big issue right now, but I do agree it needs to be done at some point.

**Comment by unnamedd** [comment]
I got it!
I'm not sure too how can we do that, but we will figure out as soon as we start this task! :)
